/* ---- PROJECT ACTIONS TYPES ---- */
export const GET_PROJECTNAMES = 'GET PROJECTNAMES'
export const GET_PROJECTNAMES_ERROR = 'GET PROJECTNAMES ERROR'

export const DELETE_PROJECT_ERROR = 'DELETE PROJECT ERROR'
export const ADD_PROJECT_ERROR = 'ADD PROJECT ERROR'

/* ---- ENDPOINT ACTIONS TYPES ---- */
export const GET_ENDPOINT_LISTS = 'GET ENDPOINT LISTS'
export const GET_ENDPOINT_LISTS_ERROR = 'GET ENDPOINT LISTS ERROR'

export const DELETE_ENDPOINT_ERROR = 'DELETE ENDPOINT ERROR'
export const UPDATE_ENDPOINT_ERROR = 'UPDATE ENDPOINT ERROR'
export const ADD_ENDPOINT_ERROR = 'ADD ENDPOINT ERROR'